Whyred Nethunter

diff --git a/META-INF/com/google/android/update-binary-anykernel b/META-INF/com/google/android/update-binary-anykernel
--- a/META-INF/com/google/android/update-binary-anykernel
+++ b/META-INF/com/google/android/update-binary-anykernel
@@ -1,17 +1,24 @@
 #!/sbin/sh
 # AnyKernel3 Backend (DO NOT CHANGE)
 # osm0sis @ xda-developers
+# modified for NetHunter
 
-OUTFD=/proc/self/fd/$2;
+##OUTFD=/proc/self/fd/$2;
 ZIPFILE="$3";
+
+## NetHuner additions
+OUTFD=$(cat /tmp/console)
+[ "$OUTFD" ] || OUTFD=/proc/$$/fd/1
 
 ps | grep zygote | grep -v grep >/dev/null && BOOTMODE=true || BOOTMODE=false;
 $BOOTMODE || ps -A 2>/dev/null | grep zygote | grep -v grep >/dev/null && BOOTMODE=true;
 
 $BOOTMODE && DIR=/sdcard || DIR=$(dirname "$ZIPFILE");
 
+
 test "$ANDROID_ROOT" || ANDROID_ROOT=/system;
-test "$home" || home=/tmp/anykernel;
+test "$home" || home=/tmp/nethunter/boot-patcher;
+
 
 ui_print() {
   until [ ! "$1" ]; do
@@ -27,7 +34,7 @@ ui_printfile() {
 show_progress() { echo "progress $1 $2" > $OUTFD; }
 file_getprop() { $bb grep "^$2=" "$1" | $bb cut -d= -f2-; }
 int2ver() {
-  if [ "$1" -eq "$1" ] 2>/dev/null; then
+  if [ "$1" -eq "$1" ] 2>/dev/null; then 
     echo "$1.0.0";
   elif [ ! "$(echo "$1" | $bb cut -d. -f3)" ]; then
     echo "$1.0";
@@ -73,30 +80,30 @@ umount_all() {
 restore_env() {
   test "$savedpath" && export LD_LIBRARY_PATH="$savedpath";
   test "$savedpre" && export LD_PRELOAD="$savedpre";
-  umount_all;
-  ($bb mv -f /system_link /system;
-  $bb mv -f /system_root_link /system_root;
-  $bb umount -l /dev/random) 2>/dev/null;
+  test "$savedlibdir" && export LIBDIR="$savedlibdir";
+  ##umount_all;
+  ##($bb mv -f /system_link /system;
+  ##$bb mv -f /system_root_link /system_root) 2>/dev/null;
 }
 abort() {
   ui_print "$@";
   debugging;
-  restore_env;
   if [ ! -f anykernel.sh -o "$(file_getprop anykernel.sh do.cleanuponabort 2>/dev/null)" == 1 ]; then
     cleanup;
   fi;
+  restore_env;
   exit 1;
 }
 
-show_progress 1.34 4;
+##show_progress 1.34 4;
 ui_print " ";
-cleanup;
+## cleanup;
 mkdir -p $home/bin;
 cd $home;
-unzip -o "$ZIPFILE";
-if [ $? != 0 -o ! "$(ls tools)" ]; then
-  abort "Unzip failed. Aborting...";
-fi;
+## unzip -o "$ZIPFILE";
+##if [ $? != 0 -o ! "$(ls tools)" ]; then
+##  abort "Unzip failed. Aborting...";
+##fi;
 for arch32 in x86 arm; do
   if [ -d $home/tools/$arch32 ]; then
     bb=$home/tools/$arch32/busybox;
@@ -127,55 +134,52 @@ if [ -f version ]; then
   ui_printfile version;
   ui_print " ";
 fi;
-ui_print " " "AGNi Kernel sdm660 by psndna88 @ xda-developers" " ";
-ui_print " " "Nethunter Kernel aditions sdm660 by S133PY @ Team-420" " ";
 ui_print " " "AnyKernel3 by osm0sis @ xda-developers" " " " ";
 
-$BOOTMODE || $bb mount -o bind /dev/urandom /dev/random;
-umount_all;
-setup_mountpoint $ANDROID_ROOT;
-if ! is_mounted $ANDROID_ROOT; then
-  $bb mount -o ro -t auto $ANDROID_ROOT;
-fi;
-case $ANDROID_ROOT in
-  /system_root) setup_mountpoint /system;;
-  /system)
-    if [ -f /system/system/build.prop ]; then
-      setup_mountpoint /system_root;
-      $bb mount --move /system /system_root;
-      if [ $? != 0 ]; then
-        $bb umount /system;
-        $bb umount -l /system 2>/dev/null;
-        $bb mount -o ro -t auto /dev/block/bootdevice/by-name/system /system_root;
-      fi;
-    fi;
-  ;;
-esac;
-if is_mounted /system_root; then
-  $bb mount -o bind /system_root/system /system;
-fi;
-$bb mount -o ro -t auto /vendor 2>/dev/null;
-if ! is_mounted /data; then
-  $bb mount /data;
-  umount_data=1;
-fi;
+##umount_all;
+##setup_mountpoint $ANDROID_ROOT;
+##if ! is_mounted $ANDROID_ROOT; then
+##  $bb mount -o ro -t auto $ANDROID_ROOT;
+##fi;
+##case $ANDROID_ROOT in
+##  /system_root) setup_mountpoint /system;;
+##  /system)
+##    if [ -f /system/system/build.prop ]; then
+##      setup_mountpoint /system_root;
+##      $bb mount --move /system /system_root;
+##      if [ $? != 0 ]; then
+##        $bb umount /system;
+##        $bb umount -l /system 2>/dev/null;
+##        $bb mount -o rw -t auto /dev/block/bootdevice/by-name/system /system_root;
+##      fi;
+##    fi;
+##  ;;
+##esac;
+##if is_mounted /system_root; then
+##  $bb mount -o bind /system_root/system /system;
+##fi;
+##$bb mount -o ro -t auto /vendor 2>/dev/null;
+##if ! is_mounted /data; then
+##  $bb mount /data;
+##  umount_data=1;
+##fi;
 
 savedpath="$LD_LIBRARY_PATH";
 savedpre="$LD_PRELOAD";
+savedlibdir="$LIBDIR";
 unset LD_LIBRARY_PATH;
 unset LD_PRELOAD;
+unset LIBDIR;
+## Let's test if that breaks something and switch back if it does (e.g. on Xiaomi Mi 9T)
+ls / >/dev/null 2>&1 || export LD_LIBRARY_PATH=${savedpath}
 
 if [ ! "$(getprop 2>/dev/null)" ]; then
   getprop() {
-    local propdir propfile propval;
-    for propdir in / /system_root /system /vendor /odm /product; do
-      for propfile in default.prop build.prop; do
-        test "$propval" && break 2 || propval="$(file_getprop $propdir/$propfile $1 2>/dev/null)";
-      done;
-    done;
+    local propval="$(file_getprop /default.prop $1 2>/dev/null)";
+    test "$propval" || local propval="$(file_getprop /system/build.prop $1 2>/dev/null)";
     test "$propval" && echo "$propval" || echo "";
   }
-elif [ ! "$(getprop ro.build.type 2>/dev/null)" ]; then
+elif [ ! "$(getprop ro.product.device 2>/dev/null)" -a ! "$(getprop ro.build.product 2>/dev/null)" ]; then
   getprop() {
     ($(which getprop) | $bb grep "$1" | $bb cut -d[ -f3 | $bb cut -d] -f1) 2>/dev/null;
   }
@@ -183,18 +187,14 @@ fi;
 
 if [ "$(file_getprop anykernel.sh do.devicecheck)" == 1 ]; then
   ui_print "Checking device...";
-  device=$(getprop ro.product.device 2>/dev/null);
-  product=$(getprop ro.build.product 2>/dev/null);
-  vendordevice=$(getprop ro.product.vendor.device 2>/dev/null);
-  vendorproduct=$(getprop ro.vendor.product.device 2>/dev/null);
+  device=$(getprop ro.product.device);
+  product=$(getprop ro.build.product);
   for testname in $(file_getprop anykernel.sh 'device.name.*'); do
-    for devicename in $device $product $vendordevice $vendorproduct; do
-      if [ "$devicename" == "$testname" ]; then
-        ui_print "$testname" " ";
-        match=1;
-        break 2;
-      fi;
-    done;
+    if [ "$device" == "$testname" -o "$product" == "$testname" ]; then
+      ui_print "$testname" " ";
+      match=1;
+      break;
+    fi;
   done;
   if [ ! "$match" ]; then
     abort " " "Unsupported device. Aborting...";
@@ -262,7 +262,7 @@ if [ "$(file_getprop anykernel.sh do.modules)" == 1 ]; then
   $bb mount -o rw,remount -t auto /system;
   $bb mount -o rw,remount -t auto /vendor 2>/dev/null;
   cd $home/modules;
-  for module in $(find . -name '*.ko'); do
+  for module in $(find . -name '*.ko' -o -name 'modules.*'); do
     modtarget=$(echo $module | $bb cut -c2-);
     if [ ! -e $modtarget ]; then
       case $module in
@@ -280,28 +280,21 @@ if [ "$(file_getprop anykernel.sh do.modules)" == 1 ]; then
     if [ "$modcon" ]; then
       chcon "u:object_r:${modcon}_file:s0" $modtarget;
     fi;
-    if is_mounted $modtarget; then
-      $bb mount -o ro,remount -t auto $modtarget;
-    fi;
+##    if is_mounted $modtarget; then
+##      $bb mount -o ro,remount -t auto $modtarget;
+##    fi;
   done;
   cd $home;
-  $bb mount -o ro,remount -t auto /system;
-  $bb mount -o ro,remount -t auto /vendor 2>/dev/null;
+##  $bb mount -o ro,remount -t auto /system;
+##  $bb mount -o ro,remount -t auto /vendor 2>/dev/null;
 fi;
 
 debugging;
-restore_env;
-
-# AGNi Wired Earphone Analog Amplification boost
-ui_print " " "AGNi now boosting Wired Earphone volume with clarity..." " ";
-$bb mount -t auto /dev/block/by-name/vendor /vendor;
-$bb sed -i '/HPHL Volume/c\    <ctl name="HPHL Volume" value="18" />' /vendor/etc/mixer_paths.xml;
-$bb sed -i '/HPHR Volume/c\    <ctl name="HPHR Volume" value="18" />' /vendor/etc/mixer_paths.xml;
-$bb umount /vendor;
 
 if [ "$(file_getprop anykernel.sh do.cleanup)" == 1 ]; then
   cleanup;
 fi;
 
-ui_print " " " " "Done!";
+restore_env;
 
+ui_print " " " " "Done!";
